### PR TITLE
improve sync routines

### PR DESCRIPTION
**Pull request by MattParr**
I'd treat this like a quick look at what I've changed, and you let me know if you are interested in incorporating it.
If you are interested, I'll do the extra work to get it back into your repo:
- naming conventions may have slipped.
- anything else you don't like.
## Not included in this pull request are two schema changes
- modified field to timeentries
- last_activity field to tickets
## What are all these changes?
- I have created an object for querying the API, which abstracts the xml process
- I have moved each sync task into it's own task.
- I have removed the autotask behaivour
- Tickets and TimeEntries are sync on change only.
## Why?

This has reduced sync times like this log below.  I can easily run my cronjob every 30 seconds.
Additionally, I do not delete tickets or timeentries, so data is saved for the future.
If you miss a few hours of syncing, reliance on the modified fields from the API means you will catch up.

```
2013-09-24 17:46:01 Cronjob: Starting CRONJOB run.
2013-09-24 17:46:01 Cronjob: Starting picklist sync
2013-09-24 17:46:06 Cronjob: Finished picklist sync
2013-09-24 17:46:06 Cronjob: Starting ticket import
2013-09-24 17:46:08 Cronjob: at query:<queryxml>
 <entity>Ticket</entity>
  <query>
   <field>LastActivityDate
    <expression op='GreaterThanorEquals'>2013-09-24 12:46:00</expression>
   </field>
  </query>
</queryxml>
2013-09-24 17:46:09 Cronjob: Retrieved 2 Tickets
2013-09-24 17:46:09 Cronjob: Converting ticket id:55507
2013-09-24 17:46:09 Cronjob: Converting ticket id:57587
2013-09-24 17:46:09 Cronjob: Finished ticket import
2013-09-24 17:46:09 Cronjob: Starting time entry import
2013-09-24 17:46:11 Cronjob: at query:<queryxml>
 <entity>TimeEntry</entity>
  <query>
   <field>LastModifiedDateTime
    <expression op='GreaterThanorEquals'>2013-09-24 12:46:00</expression>
   </field>
  </query>
</queryxml>
2013-09-24 17:46:12 Cronjob: Retrieved 1 time entries
2013-09-24 17:46:12 Cronjob: Converting time entry id:91948
2013-09-24 17:46:12 Cronjob: Finished time entry import
2013-09-24 17:46:12 Cronjob:            - Saved kill rate history for dashboard "Dash" (180 new, 158 completed)
2013-09-24 17:46:12 Cronjob:            - Saved queue health history for dashboard "Dash", queue "1st Line Support".
2013-09-24 17:46:12 Cronjob:            - Saved queue health history for dashboard "Dash", queue "2nd Line Support".
2013-09-24 17:46:12 Cronjob:            - Saved queue health history for dashboard "Dash", queue "3rd Line Support".
2013-09-24 17:46:12 Cronjob: > Calculating total open tickets for all dashboards..
2013-09-24 17:46:12 Cronjob: - Updated total open tickets count (844)
2013-09-24 17:46:12 Cronjob: ..done.
2013-09-24 17:46:12 Cronjob: > Clearing cache for all dashboards..
2013-09-24 17:46:12 Cronjob: ..done.
2013-09-24 17:46:12 Cronjob: Finished CRONJOB run.
```

### CODE REVIEW

**Comment by coencoppens** [comment]
@MattParr wow. just, wow.

I would LOVE to add this!

What would be the approach on this?

**Comment by MattParr** [comment]
@coencoppens I think maybe once you release 1.4 and tag 1.5, I will rebase with 1.5 and re-submit my pull, which should be able to just go straight on.  I'm running this now, with no problems.

I would suggest that you make the schema change for 1.4 now (eg add last_activity to ticket and modified to timeentries.  It may also be best to add all the ticket and time entry fields from the API... we have to fetch them, so we may as well store them.

I've got a few things to fix so I could use the extra time between now and then:
- timezone info is hardcoded
- save to db should be in utc (then the app can convert to the right timezone even if it moves or we bring in user level timezones (we have an office in sa)
- I think I let some of the naming conventions slip
- Now I'm keeping tickets, I need a housekeeper task that removes old records periodically.

**Comment by coencoppens** [comment]
@MattParr , I'll make the changes needed in the 1.4 branch.

I think it's convenient if we create issues for the changes you like to make; I'll do the same. I'd like to discuss the timezone change as well, I think the issues are the right place for that.

Maybe it's a smart thing to add you as a contributor to the repo? That way we can build it right in here.

**Comment by MattParr** [comment]
@coencoppens Good plan.  I am now a contributor. 

**EDIT** I get it now.  
regarding issues:  ~~I am not certain I know what you mean.~~

I could create issues for
- models: save datetime in database in UTC
- views: convert datetime from DB (UTC) into user/PHP timezone

Once the code change goes in, I could have
- need housekeeping task to remove aged tickets older than N days from config file

I can't see how I can use an issue for the goal of this pull request in general though.

**Comment by coencoppens** [comment]
@MattParr I've made you a collaborator. That way you can access the repo and go ahead and make changes without having to do pull requests.

The use of issues is more of a way for me to keep track of changes and a place for us to discuss features :-)

**Comment by MattParr** [comment]
@coencoppens Got it

**Comment by coencoppens** [comment]
@MattParr , I hope you saw the release of 1.4 :) I'm currently making changes to the sync routine too as queries are taking way too much time to my liking. Want to get in touch to discuss changes?

**Pull request closed without merging**
